ci:
  autofix_commit_msg: "\U0001F3A8 pre-commit fixes"
  autoupdate_commit_msg: "\u2B06\uFE0F\U0001FA9D update pre-commit hooks"
  skip:
    - mypy
repos:
  - hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
  - hooks:
      - args:
          - --remove-empty-cells
          - --preserve-cell-metadata
          - raw_mimetype
          - --
        id: nb-clean
    repo: https://github.com/srstevenson/nb-clean
    rev: 3.3.0
  - hooks:
      - id: fix-ligatures
      - id: fix-smartquotes
    repo: https://github.com/sirosen/texthooks
    rev: 0.6.6
  - hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
    repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
  - hooks:
      - args:
          - --fix
          - --show-fixes
        id: ruff
        types_or:
          - python
          - pyi
          - jupyter
      - id: ruff-format
        types_or:
          - python
          - pyi
          - jupyter
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
  - hooks:
      - additional_dependencies:
          - black==24.*
        id: blacken-docs
    repo: https://github.com/adamchainz/blacken-docs
    rev: 1.18.0
  - hooks:
      - additional_dependencies:
          - pyyaml
        files: (\.cmake|CMakeLists.txt)(.in)?$
        id: cmake-format
        types:
          - file
    repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13

  - hooks:
      - id: license-tools
    repo: https://github.com/emzeat/mz-lictools
    rev: v2.7.0
  - hooks:
      - id: clang-format
        types_or:
          - c++
          - c
          - cuda
    repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
  - hooks:
      - id: prettier
        types_or:
          - yaml
          - markdown
          - html
          - css
          - scss
          - javascript
          - json
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
  - hooks:
      - additional_dependencies:
          - importlib_resources
          - numpy
          - pytest
        args: []
        files: ^(src/mqt|test/python)
        id: mypy
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
  - hooks:
      - args:
          - -L
          - wille,linz,astroid
          - --skip
          - "*.ipynb"
        id: codespell
    repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
  - hooks:
      - entry: PyBind|Numpy|Cmake|CCache|Github|PyTest|Mqt|Tum
        exclude: .pre-commit-config.yaml
        id: disallow-caps
        language: pygrep
        name: Disallow improper capitalization
    repo: local
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push
    repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
